#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Writes the US-JIS test cases in tests/zmk/ (run by scripts/run-zmk-tests.sh).

Each case is a ZMK native_sim test: a keymap with mock key events, and the
expected log (keycode_events.snapshot) of every HID report that is sent
(tests/zmk/report-log) and of the mode changes. The expected reports are
written here from docs/usjis-substitution.md: the table of section 4 and the
scenarios S01-S20 of section 10. They are not produced by running the
firmware.

    python3 tests/zmk/generate.py           # write the cases
    python3 tests/zmk/generate.py --check   # fail if the written cases differ
"""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

PATTERNS = r"""s/^report: //p
s/^usjis: \(listener order [a-z]*\).*/\1/p
s/^usjis: \(mode .*\)/\1/p
s/^usjis: \(applying pending mode\)/\1/p
s/^usjis: \(HID state cleared by endpoint switch\).*/\1/p
"""

# Keyboard page usages (HID Usage Tables, keyboard/keypad page).
A, X, N1, N2, N6, N7, N8, N9, N0 = 0x04, 0x1B, 0x1E, 0x1F, 0x23, 0x24, 0x25, 0x26, 0x27
MINUS, EQUAL, LBKT, RBKT, BSLH, SEMI, SQT, GRAVE = 0x2D, 0x2E, 0x2F, 0x30, 0x31, 0x33, 0x34, 0x35
F24, INT5 = 0x73, 0x8B
# JIS host positions (spec section 4, second table).
JIS_CARET, JIS_AT, JIS_LBKT, JIS_RBKT, JIS_COLON, JIS_RO, JIS_YEN = (
    0x2E, 0x2F, 0x30, 0x32, 0x34, 0x87, 0x89)
LCTL, LSFT, LALT, RSFT = 0x01, 0x02, 0x04, 0x20
C_VOL_UP = 0xE9

# Spec section 4: (id, input usage, input Shift, output usage, output Shift).
TABLE = [
    ("C01", GRAVE, True, JIS_CARET, True),
    ("C02", N2, True, JIS_AT, False),
    ("C03", N6, True, JIS_CARET, False),
    ("C04", N7, True, N6, True),
    ("C05", N8, True, JIS_COLON, True),
    ("C06", N9, True, N8, True),
    ("C07", N0, True, N9, True),
    ("C08", MINUS, True, JIS_RO, True),
    ("C09", EQUAL, False, MINUS, True),
    ("C10", EQUAL, True, SEMI, True),
    ("C11", LBKT, False, JIS_LBKT, False),
    ("C12", LBKT, True, JIS_LBKT, True),
    ("C13", RBKT, False, JIS_RBKT, False),
    ("C14", RBKT, True, JIS_RBKT, True),
    ("C15", BSLH, False, JIS_RO, False),
    ("C16", BSLH, True, JIS_YEN, True),
    ("C17", SEMI, True, JIS_COLON, False),
    ("C18", SQT, False, N7, True),
    ("C19", SQT, True, N2, True),
    ("C20", GRAVE, False, JIS_AT, True),
]

ZMK_NAMES = {GRAVE: "GRAVE", N2: "N2", N6: "N6", N7: "N7", N8: "N8", N9: "N9", N0: "N0",
             MINUS: "MINUS", EQUAL: "EQUAL", LBKT: "LBKT", RBKT: "RBKT", BSLH: "BSLH",
             SEMI: "SEMI", SQT: "SQT"}


def kbd(mods, *keys):
    return "kbd {%02X,[%s]}" % (mods, " ".join("%02X" % k for k in sorted(keys)))


def consumer(*usages):
    return "consumer [%s]" % " ".join("%04X" % u for u in sorted(usages))


class Case:
    """One native_sim test: the positions of a one-row keymap (or a full keymap
    body), the mock events and the expected log."""

    def __init__(self, name, conf, bindings=None, keymap=None, columns=None):
        self.name, self.conf = name, conf
        self.bindings, self.keymap = bindings, keymap
        self.columns = columns or len(bindings)
        self.events, self.expected = [], []
        self.pos = {b: i for i, b in enumerate(bindings or [])}

    def _col(self, key):
        return key if isinstance(key, int) else self.pos[key]

    def press(self, key, wait=10):
        self.events.append("ZMK_MOCK_PRESS(0,%d,%d)" % (self._col(key), wait))

    def release(self, key, wait=10):
        self.events.append("ZMK_MOCK_RELEASE(0,%d,%d)" % (self._col(key), wait))

    def tap(self, key):
        self.press(key)
        self.release(key)

    def expect(self, *lines):
        self.expected.extend(lines)

    def separator(self):
        """A tap of F24 between scenarios, so that a difference is easy to place."""
        self.tap("&kp F24")
        self.expect(kbd(0, F24), kbd(0))

    def files(self):
        if self.keymap is None:
            body = "\n".join("                " + b for b in self.bindings)
            keymap_body = """    keymap {
        compatible = "zmk,keymap";
        default_layer {
            bindings = <
%s
            >;
        };
    };""" % body
        else:
            keymap_body = self.keymap
        events = "\n".join("        " + e for e in self.events)
        keymap = """/* Generated by tests/zmk/generate.py; do not edit. */
#include <dt-bindings/zmk/keys.h>
#include <behaviors.dtsi>
#include <dt-bindings/zmk/kscan_mock.h>
#include <dt-bindings/zmk/usjis.h>

&kscan {
    rows = <1>;
    columns = <%d>;
    events = <
%s
    >;
};

/ {
    behaviors {
        usjis: usjis {
            compatible = "zmk,behavior-usjis";
            #binding-cells = <1>;
        };
        test_clear: test_clear {
            compatible = "zmk,behavior-test-clear";
            #binding-cells = <0>;
        };
    };
};

/ {
%s
};
""" % (self.columns, events, keymap_body)
        conf = "# Generated by tests/zmk/generate.py; do not edit.\n" + "".join(
            line + "\n" for line in ["CONFIG_LOG_MODE_IMMEDIATE=y", "CONFIG_ZMK_USJIS_LOG_LEVEL=3"] +
            self.conf)
        return {
            "native_sim.keymap": keymap,
            "native_sim.conf": conf,
            "events.patterns": PATTERNS,
            "keycode_events.snapshot": "".join(line + "\n" for line in self.expected),
        }


# ------------------------------------------------------------------ table

SHIFTS = {"left": [("&kp LSHFT", LSFT)], "right": [("&kp RSHFT", RSFT)],
          "both": [("&kp LSHFT", LSFT), ("&kp RSHFT", RSFT)]}


def shifted_sequence(case, key, in_usage, out_usage, out_mods, shifts, key_first):
    """Shift(s) down, key down, then the key or the Shift(s) up first.
    out_usage/out_mods: what the key reports while held (substituted or not)."""
    held = 0
    for binding, bit in shifts:
        case.press(binding)
        held |= bit
        case.expect(kbd(held))
    case.press(key)
    case.expect(kbd(out_mods, out_usage))
    substituted = out_usage != in_usage
    if key_first:
        case.release(key)
        case.expect(kbd(held))
        for binding, bit in reversed(shifts):
            case.release(binding)
            held &= ~bit
            case.expect(kbd(held))
    else:
        for binding, bit in reversed(shifts):
            case.release(binding)
            held &= ~bit
            # Substituted: the key keeps its own modifiers (spec S03, S14).
            # Identity: the physical Shift that is left.
            case.expect(kbd(out_mods if substituted else held, out_usage))
        case.release(key)
        case.expect(kbd(0))


def table_case():
    keys = ["&kp " + ZMK_NAMES[u] for u in ZMK_NAMES]
    bindings = ["&kp LSHFT", "&kp RSHFT"] + keys + [
        "&kp N1", "&kp PLUS", "&kp LC(EQUAL)", "&kp F24", "&usjis USJIS_TOG"]
    case = Case("usjis-table", ["CONFIG_ZMK_USJIS_DEFAULT_ENABLED=y",
                                "CONFIG_ZMK_USJIS_LAYER_MASK=0"], bindings)
    case.expect("listener order ok")

    def run_table(enabled):
        for cid, in_usage, in_shift, out_usage, out_shift in TABLE:
            key = "&kp " + ZMK_NAMES[in_usage]
            if enabled:
                usage, mods = out_usage, LSFT if out_shift else 0
            if in_shift:
                for variant in ("left", "right", "both"):
                    for key_first in (True, False):
                        if not enabled:
                            usage = in_usage
                            mods = sum(bit for _, bit in SHIFTS[variant])
                        shifted_sequence(case, key, in_usage, usage, mods, SHIFTS[variant],
                                         key_first)
            else:
                case.tap(key)
                case.expect(kbd(mods, usage) if enabled else kbd(0, in_usage), kbd(0))
            case.separator()

    # C01-C20 with the mode enabled.
    run_table(True)
    # Chords outside the table stay identity (spec section 5).
    for usage in (N2, N6, N7, N8, N9, N0, MINUS, SEMI):
        case.tap("&kp " + ZMK_NAMES[usage])
        case.expect(kbd(0, usage), kbd(0))
    shifted_sequence(case, "&kp N1", N1, N1, RSFT, SHIFTS["right"], True)
    case.separator()
    # Shift from the key's own binding matches (&kp PLUS = LS(EQUAL) is C10);
    # Ctrl is kept (LC(EQUAL) is C09 plus Ctrl).
    case.tap("&kp PLUS")
    case.expect(kbd(LSFT, SEMI), kbd(0))
    case.tap("&kp LC(EQUAL)")
    case.expect(kbd(LCTL | LSFT, MINUS), kbd(0))
    case.separator()
    # S01: disabled, every chord is identity.
    case.tap("&usjis USJIS_TOG")
    case.expect("mode DISABLED")
    run_table(False)
    case.tap("&kp PLUS")
    case.expect(kbd(LSFT, EQUAL), kbd(0))
    case.tap("&kp LC(EQUAL)")
    case.expect(kbd(LCTL, EQUAL), kbd(0))
    return case


# -------------------------------------------------------------- scenarios

def scenarios_case():
    bindings = ["&kp RSHFT", "&kp N2", "&kp MINUS", "&kp A", "&kp EQUAL", "&usjis USJIS_TOG",
                "&usjis USJIS_ON", "&usjis USJIS_OFF", "&kp LS(A)", "&kp LC(X)", "&kp LALT",
                "&kp C_VOL_UP", "&kp F24", "&test_clear"]
    c = Case("usjis-scenarios", ["CONFIG_ZMK_USJIS_DEFAULT_ENABLED=y",
                                 "CONFIG_ZMK_USJIS_LAYER_MASK=0"], bindings)
    RS, TWO, MIN, KA, EQ = "&kp RSHFT", "&kp N2", "&kp MINUS", "&kp A", "&kp EQUAL"
    TOG, ON, OFF = "&usjis USJIS_TOG", "&usjis USJIS_ON", "&usjis USJIS_OFF"
    c.expect("listener order ok")

    # S02
    c.press(RS); c.press(TWO); c.release(TWO); c.release(RS)
    c.expect(kbd(RSFT), kbd(0, JIS_AT), kbd(RSFT), kbd(0))
    c.separator()
    # S03
    c.press(RS); c.press(TWO); c.release(RS); c.release(TWO)
    c.expect(kbd(RSFT), kbd(0, JIS_AT), kbd(0, JIS_AT), kbd(0))
    c.separator()
    # S05
    c.press(RS); c.press(TWO); c.press(MIN); c.release(MIN); c.release(TWO); c.release(RS)
    c.expect(kbd(RSFT), kbd(0, JIS_AT), kbd(LSFT, JIS_AT, JIS_RO), kbd(0, JIS_AT), kbd(RSFT),
             kbd(0))
    c.separator()
    # S06: a held substituted key sends nothing more during one second.
    c.press(EQ, wait=1000); c.release(EQ)
    c.expect(kbd(LSFT, MINUS), kbd(0))
    c.separator()
    # S07 (enabled): a consumer usage is unchanged.
    c.tap("&kp C_VOL_UP")
    c.expect(consumer(C_VOL_UP), consumer())
    c.separator()
    # S11
    c.press(RS); c.press(TWO); c.press(KA); c.release(KA); c.release(TWO); c.release(RS)
    c.expect(kbd(RSFT), kbd(0, JIS_AT), kbd(RSFT, A, JIS_AT), kbd(0, JIS_AT), kbd(RSFT), kbd(0))
    c.separator()
    # S12
    c.press(EQ); c.press(KA); c.release(KA); c.release(EQ)
    c.expect(kbd(LSFT, MINUS), kbd(0, A, MINUS), kbd(LSFT, MINUS), kbd(0))
    c.separator()
    # S13
    c.press(EQ); c.press(RS); c.press(TWO); c.release(TWO); c.release(RS); c.release(EQ)
    c.expect(kbd(LSFT, MINUS), kbd(LSFT, MINUS), kbd(0, MINUS, JIS_AT), kbd(LSFT, MINUS),
             kbd(LSFT, MINUS), kbd(0))
    c.separator()
    # S14
    c.press(RS); c.press(MIN); c.release(RS); c.release(MIN)
    c.expect(kbd(RSFT), kbd(LSFT, JIS_RO), kbd(LSFT, JIS_RO), kbd(0))
    c.separator()
    # S18: the Shift of LS(A) is not restored after C09 is released.
    c.press("&kp LS(A)"); c.press(EQ); c.release(EQ); c.release("&kp LS(A)")
    c.expect(kbd(LSFT, A), kbd(LSFT, A, MINUS), kbd(0, A), kbd(0))
    c.separator()
    # S19: no keyboard report loses the added Shift of C09 while it is held.
    c.press(KA); c.press(EQ); c.release(KA)
    c.tap("&kp C_VOL_UP")
    c.release(EQ)
    c.expect(kbd(0, A), kbd(LSFT, A, MINUS), kbd(LSFT, MINUS), consumer(C_VOL_UP), consumer(),
             kbd(0))
    c.separator()
    # S20: the Ctrl of LC(X) is not restored once removed, not even by Alt.
    c.press(EQ); c.press("&kp LC(X)"); c.press(KA); c.release(KA)
    c.press("&kp LALT"); c.release("&kp LALT"); c.release("&kp LC(X)"); c.release(EQ)
    c.expect(kbd(LSFT, MINUS), kbd(LCTL, X, MINUS), kbd(0, A, X, MINUS), kbd(0, X, MINUS),
             kbd(LALT, X, MINUS), kbd(0, X, MINUS), kbd(LSFT, MINUS), kbd(0))
    c.separator()
    # S17: the endpoint changes (the switch moves between BT and cable) while
    # C09 is held. Nothing after it carries C09's usage or Shift, its release
    # sends nothing, and no press record is left: a toggle applies at once.
    c.press(EQ); c.tap("&test_clear"); c.press(RS); c.tap(KA); c.release(RS); c.release(EQ)
    c.expect(kbd(LSFT, MINUS), "endpoint clear", "HID state cleared by endpoint switch",
             kbd(RSFT), kbd(RSFT, A), kbd(RSFT), kbd(0))
    c.tap(TOG)
    c.expect("mode DISABLED")
    c.tap(TOG)
    c.expect("mode ENABLED")
    c.tap(EQ)
    c.expect(kbd(LSFT, MINUS), kbd(0))
    c.separator()
    # S04 and S08: OFF while C09 is held is applied after its release; the
    # mode keys send nothing.
    c.press(EQ); c.tap(OFF); c.release(EQ)
    c.expect(kbd(LSFT, MINUS), "mode request DISABLED pending", kbd(0), "applying pending mode",
             "mode DISABLED")
    c.tap(EQ)
    c.expect(kbd(0, EQUAL), kbd(0))
    # S07 (disabled)
    c.tap("&kp C_VOL_UP")
    c.expect(consumer(C_VOL_UP), consumer())
    c.separator()
    # S15. The release of A is not substituted: the pending mode is applied
    # before hid_listener reports the release.
    c.press(KA); c.tap(ON); c.press(RS); c.tap(TWO); c.release(KA); c.tap(TWO); c.release(RS)
    c.expect(kbd(0, A), "mode request ENABLED pending", kbd(RSFT, A), kbd(RSFT, A, N2),
             kbd(RSFT, A), "applying pending mode", "mode ENABLED", kbd(RSFT), kbd(0, JIS_AT),
             kbd(RSFT), kbd(0))
    c.separator()
    # S16: two toggles while C09 is held cancel each other.
    c.press(EQ); c.tap(TOG); c.tap(TOG); c.release(EQ)
    c.expect(kbd(LSFT, MINUS), "mode request DISABLED pending", "mode request ENABLED pending",
             kbd(0))
    c.tap(EQ)
    c.expect(kbd(LSFT, MINUS), kbd(0))
    # ON while enabled and OFF while disabled change nothing (spec section 3).
    c.tap(ON)
    c.tap(TOG)
    c.expect("mode DISABLED")
    c.tap(OFF)
    c.tap(TOG)
    c.expect("mode ENABLED")
    c.separator()
    return c


# ----------------------------------------------------------------- layers

LAYERS_KEYMAP = """    behaviors {
        ime_ht: ime_hold_tap {
            compatible = "zmk,behavior-hold-tap";
            #binding-cells = <2>;
            flavor = "hold-preferred";
            tapping-term-ms = <200>;
            bindings = <&kp>, <&kp>;
        };
    };

    /* The B1 Pro's layers: 0 Mac, 1 Mac Fn, 2 Win (held by the OS switch),
     * 3 Win Fn. Fn+Tab toggles the mode, which applies in Win only. */
    keymap {
        compatible = "zmk,keymap";
        mac {
            bindings = <&kp EQUAL &mo 1 &kp TAB &mo 2 &ime_ht LALT INT5 &kp RSHFT &kp N2 &kp F24>;
        };
        mac_fn {
            bindings = <&trans &trans &usjis USJIS_TOG &trans &trans &trans &trans &trans>;
        };
        win {
            bindings = <&trans &mo 3 &trans &trans &trans &trans &trans &trans>;
        };
        win_fn {
            bindings = <&trans &trans &usjis USJIS_TOG &trans &trans &trans &trans &trans>;
        };
    };"""


def layers_case():
    c = Case("usjis-layers", [], keymap=LAYERS_KEYMAP, columns=8)
    EQ, FN, TAB, WIN, IME, RS, TWO, SEP = range(8)
    c.expect("listener order ok")
    # Disabled by default (no stored setting).
    c.tap(EQ)
    c.expect(kbd(0, EQUAL), kbd(0))
    # Mac Fn+Tab enables the mode; Mac stays identity (layer mask 0x04).
    c.press(FN); c.tap(TAB); c.release(FN)
    c.expect("mode ENABLED")
    c.tap(EQ)
    c.expect(kbd(0, EQUAL), kbd(0))
    # The Win position (&mo 2 held) substitutes.
    c.press(WIN)
    c.tap(EQ)
    c.expect(kbd(LSFT, MINUS), kbd(0))
    c.press(RS); c.tap(TWO); c.release(RS)
    c.expect(kbd(RSFT), kbd(0, JIS_AT), kbd(RSFT), kbd(0))
    # The IME hold-tap held as Alt: Alt is kept on a substituted key.
    c.press(IME); c.tap(EQ); c.release(IME)
    c.expect(kbd(LALT), kbd(LALT | LSFT, MINUS), kbd(LALT), kbd(0))
    # Tapped, it sends Muhenkan (INT5), not substituted.
    c.tap(IME)
    c.expect(kbd(0, INT5), kbd(0))
    c.tap(SEP)
    c.expect(kbd(0, F24), kbd(0))
    # Win Fn+Tab disables it.
    c.press(FN); c.tap(TAB); c.release(FN)
    c.expect("mode DISABLED")
    c.tap(EQ)
    c.expect(kbd(0, EQUAL), kbd(0))
    c.release(WIN)
    return c


def main():
    check = "--check" in sys.argv[1:]
    stale = []
    for case in (table_case(), scenarios_case(), layers_case()):
        out = HERE / case.name
        for name, text in case.files().items():
            path = out / name
            if check:
                if not path.is_file() or path.read_text() != text:
                    stale.append(str(path.relative_to(HERE.parent.parent)))
            else:
                out.mkdir(exist_ok=True)
                path.write_text(text)
    if stale:
        print("Out of date (run python3 tests/zmk/generate.py):", *stale, sep="\n  ")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
